// Builds the SQL that (re)creates the "Motio QA Playground" workspace on the
// testing stand from the /demo seed (src/features/demo/lib/demoSeed.ts), so the
// stand and the public sandbox show the same team, projects and tasks.
//
// Dates are written as offsets from the database's current_date, so the
// timeline is centred on the day the seed runs. Rerunning deletes the workspace
// (everything under it cascades) and builds it again.
//
// Driven by infra/scripts/seed-testing.sh (`make seed-testing`):
//   build-seed-sql.ts          prints the SQL
//   build-seed-sql.ts --emails prints the accounts the SQL expects
//
// SEED_TESTING_EXTRA_MEMBERS ("email:role,email:role") adds real people to the
// playground on top of the QA accounts. The script takes it from the testing
// server's .env, so personal addresses stay out of this public repository.

import {
  DEMO_SEED_ASSIGNEES,
  DEMO_SEED_ASSIGNEE_COLORS,
  DEMO_SEED_CUSTOMERS,
  DEMO_SEED_CUSTOMER_CONTACTS,
  DEMO_SEED_DASHBOARDS,
  DEMO_SEED_MILESTONES,
  DEMO_SEED_PROJECTS,
  DEMO_SEED_PROJECT_CUSTOMER,
  DEMO_SEED_PROJECT_MEMBERS,
  DEMO_SEED_STATUSES,
  DEMO_SEED_TAGS,
  DEMO_SEED_TASKS,
  DEMO_SEED_TASK_TYPES,
  DEMO_SEED_TIME_OFF,
  buildDemoDashboardLayouts,
} from '../../../src/features/demo/lib/demoSeed';

const WORKSPACE_ID = 'a11ce000-5eed-4000-8000-000000000001';
const WORKSPACE_NAME = 'Motio QA Playground';

// QA accounts of the testing Keycloak, mapped onto the seed's "QA …" teammates
// so their tasks become the testers' own. Roles cover every permission level.
// qa.newbie stays out on purpose: it is the account for testing a first sign-in.
const QA_MEMBERS = [
  { email: 'qa.alice.playground@motio.test', assigneeId: '22222222-0000-0000-0000-000000000008', role: 'admin' },
  { email: 'qa.bob.playground@motio.test', assigneeId: '22222222-0000-0000-0000-000000000009', role: 'editor' },
  { email: 'qa.carol.playground@motio.test', assigneeId: '22222222-0000-0000-0000-000000000010', role: 'editor' },
  { email: 'qa.dave.playground@motio.test', assigneeId: '22222222-0000-0000-0000-000000000011', role: 'viewer' },
] as const;

const OWNER_EMAIL = QA_MEMBERS[0].email;

const WORKSPACE_ROLES = ['admin', 'editor', 'viewer'] as const;
type WorkspaceRole = (typeof WORKSPACE_ROLES)[number];

const parseExtraMembers = (raw: string): { email: string; role: WorkspaceRole }[] =>
  raw
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => {
      const [emailPart, rolePart = ''] = entry.split(':');
      const email = emailPart.trim().toLowerCase();
      const role = rolePart.trim() as WorkspaceRole;
      if (!/^[^\s@:,']+@[^\s@:,']+\.[^\s@:,']+$/.test(email)) {
        throw new Error(`SEED_TESTING_EXTRA_MEMBERS: "${entry}" has no valid email`);
      }
      if (!WORKSPACE_ROLES.includes(role)) {
        throw new Error(`SEED_TESTING_EXTRA_MEMBERS: "${entry}" needs a role of ${WORKSPACE_ROLES.join('/')}`);
      }
      if (QA_MEMBERS.some((m) => m.email === email)) {
        throw new Error(`SEED_TESTING_EXTRA_MEMBERS: ${email} is already a QA member`);
      }
      return { email, role };
    });

// Real people join as themselves: the member-sync trigger gives each one an
// assignee under their profile name, without seed tasks of their own.
const EXTRA_MEMBERS = parseExtraMembers(process.env.SEED_TESTING_EXTRA_MEMBERS ?? '');
const ALL_MEMBERS = [...QA_MEMBERS.map(({ email, role }) => ({ email, role })), ...EXTRA_MEMBERS];

const lit = (value: string | number | boolean | null | undefined): string => {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return `'${value.replace(/'/g, "''")}'`;
};
const uuidArray = (ids: readonly string[]) =>
  ids.length > 0 ? `array[${ids.map(lit).join(', ')}]::uuid[]` : `'{}'::uuid[]`;
const jsonb = (value: unknown) => `${lit(JSON.stringify(value))}::jsonb`;
const day = (offset: number) => `current_date + ${offset}`;
const userId = (email: string) => `(select id from auth.users where lower(email) = ${lit(email)})`;
// The app lists statuses, projects, people and contacts by created_at, so the
// seed's sort order becomes one-second steps in the recent past.
const orderedAt = (position: number) => `now() - interval '10 minutes' + ${position} * interval '1 second'`;

const insert = (table: string, columns: string[], rows: string[][]) =>
  `insert into public.${table} (${columns.join(', ')}) values\n${rows
    .map((row) => `  (${row.join(', ')})`)
    .join(',\n')};`;

const W = lit(WORKSPACE_ID);
const memberByAssignee = new Map<string, (typeof QA_MEMBERS)[number]>(QA_MEMBERS.map((m) => [m.assigneeId, m]));

const buildSql = (): string => {
  const parts: string[] = [];

  parts.push(`-- Generated by infra/scripts/seed-testing/build-seed-sql.ts from
-- src/features/demo/lib/demoSeed.ts. Do not edit; rerun \`make seed-testing\`.
-- Runs as one transaction on the testing database only.`);

  const emailList = `array[${ALL_MEMBERS.map((m) => lit(m.email)).join(', ')}]`;
  parts.push(`do $$
declare
  missing text;
begin
  select string_agg(wanted.email, ', ')
    into missing
  from unnest(${emailList}) as wanted(email)
  where not exists (select 1 from auth.users u where lower(u.email) = wanted.email);
  if missing is not null then
    raise exception 'QA accounts are missing in auth.users: %', missing;
  end if;
end $$;`);

  // Everything under the workspace cascades; every rerun also exercises the
  // real workspace deletion (0149).
  parts.push(`delete from public.workspaces where id = ${W};`);

  // Linked people show their profile name, so the testers carry the seed's names.
  parts.push(
    QA_MEMBERS.map((m) => {
      const name = DEMO_SEED_ASSIGNEES.find((a) => a.id === m.assigneeId)?.name ?? m.email;
      return `update public.profiles set display_name = ${lit(name)} where id = ${userId(m.email)};`;
    }).join('\n'),
  );

  parts.push(
    insert('workspaces', ['id', 'name', 'owner_id', 'heatmap_enabled'], [
      [W, lit(WORKSPACE_NAME), userId(OWNER_EMAIL), 'true'],
    ]),
  );

  parts.push(
    insert('statuses', ['id', 'workspace_id', 'name', 'color', 'is_final', 'is_cancelled', 'created_at'],
      DEMO_SEED_STATUSES.map((s) => [lit(s.id), W, lit(s.name), lit(s.color), lit(s.is_final), lit(s.is_cancelled), orderedAt(s.sort_order)])),
  );
  parts.push(
    insert('task_types', ['id', 'workspace_id', 'name', 'icon', 'created_at'],
      DEMO_SEED_TASK_TYPES.map((t) => [lit(t.id), W, lit(t.name), lit(t.icon), orderedAt(t.sort_order)])),
  );
  parts.push(
    insert('tags', ['id', 'workspace_id', 'name', 'color', 'created_at'],
      DEMO_SEED_TAGS.map((t) => [lit(t.id), W, lit(t.name), lit(t.color), orderedAt(t.sort_order)])),
  );
  parts.push(
    insert('customers', ['id', 'workspace_id', 'name', 'industry', 'created_at'],
      DEMO_SEED_CUSTOMERS.map((c, index) => [lit(c.id), W, lit(c.name), lit(c.industry), orderedAt(index)])),
  );
  parts.push(
    insert('customer_contacts', ['id', 'workspace_id', 'customer_id', 'name', 'role', 'email', 'phone', 'company', 'tag', 'position', 'created_at'],
      DEMO_SEED_CUSTOMER_CONTACTS.map((c, index) => [
        lit(c.id), W, lit(c.customer_id), lit(c.name), lit(c.role), lit(c.email), lit(c.phone), lit(c.company), lit(c.tag), lit(c.position), orderedAt(index),
      ])),
  );
  parts.push(
    insert('projects', ['id', 'workspace_id', 'name', 'color', 'customer_id', 'created_at'],
      DEMO_SEED_PROJECTS.map((p) => [lit(p.id), W, lit(p.name), lit(p.color), lit(DEMO_SEED_PROJECT_CUSTOMER[p.id] ?? null), orderedAt(p.sort_order)])),
  );

  // People first, members second: adding a member upserts the assignee linked
  // to that user, so the linked rows must already carry the seed's ids.
  parts.push(
    insert('assignees', ['id', 'workspace_id', 'user_id', 'name', 'is_active', 'color', 'created_at'],
      DEMO_SEED_ASSIGNEES.map((a) => {
        const member = memberByAssignee.get(a.id);
        return [lit(a.id), W, member ? userId(member.email) : 'null', lit(a.name), 'true', lit(DEMO_SEED_ASSIGNEE_COLORS[a.id] ?? null), orderedAt(a.sort_order)];
      })),
  );
  parts.push(
    insert('workspace_members', ['workspace_id', 'user_id', 'role'],
      ALL_MEMBERS.map((m) => [W, userId(m.email), lit(m.role)])),
  );

  parts.push(
    insert('tasks', ['id', 'workspace_id', 'title', 'project_id', 'assignee_id', 'assignee_ids', 'start_date', 'end_date', 'status_id', 'type_id', 'priority', 'tag_ids', 'description'],
      DEMO_SEED_TASKS.map((t) => [
        lit(t.id), W, lit(t.title), lit(t.project_id), lit(t.assignee_ids[0] ?? null), uuidArray(t.assignee_ids),
        day(t.start_offset_days), day(t.end_offset_days), lit(t.status_id), lit(t.type_id), lit(t.priority), uuidArray(t.tag_ids), lit(t.description),
      ])),
  );
  parts.push(
    insert('time_off', ['id', 'workspace_id', 'assignee_id', 'start_date', 'end_date', 'note'],
      DEMO_SEED_TIME_OFF.map((r) => [lit(r.id), W, lit(r.assignee_id), day(r.start_offset_days), day(r.end_offset_days), lit(r.note)])),
  );
  parts.push(
    insert('milestones', ['id', 'workspace_id', 'project_id', 'date', 'title'],
      DEMO_SEED_MILESTONES.map((m) => [lit(m.id), W, lit(m.project_id), day(m.offset_days), lit(m.title)])),
  );
  parts.push(
    insert('project_members', ['id', 'workspace_id', 'project_id', 'assignee_id', 'role', 'tag', 'external_name', 'external_company', 'external_email', 'external_phone', 'position'],
      DEMO_SEED_PROJECT_MEMBERS.map((m) => [
        lit(m.id), W, lit(m.project_id), lit(m.assignee_id), lit(m.role), lit(m.tag),
        lit(m.external_name), lit(m.external_company), lit(m.external_email), lit(m.external_phone), lit(m.position),
      ])),
  );
  parts.push(
    insert('workspace_dashboards', ['id', 'workspace_id', 'name', 'widgets', 'layouts'],
      DEMO_SEED_DASHBOARDS.map((d) => [lit(d.id), W, lit(d.name), jsonb(d.widgets), jsonb(buildDemoDashboardLayouts(d.widgets))])),
  );

  // Seeding is nobody assigning anyone a task: drop what the assignment
  // trigger wrote, so the testers' inboxes start empty.
  parts.push(`delete from public.user_notifications where workspace_id = ${W};`);

  parts.push(`select 'Seeded ${WORKSPACE_NAME}: '
  || (select count(*) from public.tasks where workspace_id = ${W}) || ' tasks, '
  || (select count(*) from public.projects where workspace_id = ${W}) || ' projects, '
  || (select count(*) from public.assignees where workspace_id = ${W}) || ' people, '
  || (select count(*) from public.workspace_members where workspace_id = ${W}) || ' members, '
  || (select count(*) from public.milestones where workspace_id = ${W}) || ' milestones' as result;`);

  return `${parts.join('\n\n')}\n`;
};

if (process.argv.includes('--emails')) {
  process.stdout.write(`${ALL_MEMBERS.map((m) => m.email).join('\n')}\n`);
} else {
  process.stdout.write(buildSql());
}
