#!/usr/bin/env bash
set -euo pipefail

# CI guardrail against the root cause of finding C-1: a SECURITY DEFINER function
# that forgot `REVOKE ... FROM PUBLIC` is callable by anon/authenticated and runs
# with the owner's privileges (RLS bypass).
#
# Rule: every SECURITY DEFINER function in infra/supabase/migrations/*.sql must
# EITHER have a `REVOKE ... ON FUNCTION <name> ... FROM ... (public|anon|
# authenticated)` somewhere in the migrations, OR be listed in the baseline
# allowlist (for functions that are intentionally callable by clients, e.g. RLS
# helpers). A NEW SECURITY DEFINER function that is neither revoked nor
# allowlisted fails CI — forcing a conscious decision.
#
# Regenerate the baseline after an intentional review:
#   infra/scripts/lint-security-definer.sh --write-baseline

if [[ -n "${BASH_SOURCE[0]:-}" && -f "${BASH_SOURCE[0]}" ]]; then
  root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
  cd "$root_dir"
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required to run the SECURITY DEFINER lint." >&2
  exit 1
fi

MODE="check"
if [[ "${1:-}" == "--write-baseline" ]]; then
  MODE="write"
fi

MODE="$MODE" python3 - <<'PY'
import glob, os, re, sys

MIGRATIONS = sorted(glob.glob("infra/supabase/migrations/*.sql"))
ALLOWLIST = "infra/scripts/security-definer-allowlist.txt"
MODE = os.environ.get("MODE", "check")

create_re = re.compile(r"create\s+(?:or\s+replace\s+)?function\s+(?:public\.)?([a-z0-9_]+)\s*\(", re.I)

definer = {}   # name -> set(files) where it is defined SECURITY DEFINER
revoked = set()

for path in MIGRATIONS:
    text = open(path, encoding="utf-8").read()
    base = os.path.basename(path)

    # REVOKE ... ON FUNCTION <name>( ... ) ... FROM <targets> ;  (public/anon/authenticated)
    for m in re.finditer(
        r"revoke\s+[^;]*?on\s+function\s+(?:public\.)?([a-z0-9_]+)\s*\([^;]*?from\s+([^;]*?);",
        text, re.I | re.S,
    ):
        name, targets = m.group(1), m.group(2).lower()
        if any(t in targets for t in ("public", "anon", "authenticated")):
            revoked.add(name)

    # Associate each `security definer` with the function whose CREATE block it is in.
    hits = [(m.start(), m.group(1)) for m in create_re.finditer(text)]
    for i, (pos, name) in enumerate(hits):
        end = hits[i + 1][0] if i + 1 < len(hits) else len(text)
        if re.search(r"security\s+definer", text[pos:end], re.I):
            definer.setdefault(name, set()).add(base)

flagged = sorted(n for n in definer if n not in revoked)

if MODE == "write":
    with open(ALLOWLIST, "w", encoding="utf-8") as fh:
        fh.write("# Baseline of SECURITY DEFINER functions intentionally callable by\n")
        fh.write("# clients (no REVOKE from public). Generated by\n")
        fh.write("#   infra/scripts/lint-security-definer.sh --write-baseline\n")
        fh.write("# A NEW definer function must add a REVOKE, not be appended here without review.\n")
        for n in flagged:
            fh.write(n + "\n")
    print(f"Wrote baseline allowlist ({len(flagged)} functions) to {ALLOWLIST}")
    sys.exit(0)

allow = set()
if os.path.exists(ALLOWLIST):
    for line in open(ALLOWLIST, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if line:
            allow.add(line)

violations = [n for n in flagged if n not in allow]

if violations:
    print("SECURITY DEFINER functions without REVOKE from public/anon/authenticated and not allowlisted:")
    for n in violations:
        print(f"  - {n}  (defined in: {', '.join(sorted(definer[n]))})")
    print("")
    print("Fix ONE of:")
    print("  1. Add: revoke all on function public.<name>(<args>) from public, anon, authenticated;")
    print("     (+ keep any needed `grant execute ... to service_role;`)")
    print(f"  2. If it is intentionally client-callable (e.g. an RLS helper), add its name to {ALLOWLIST}.")
    sys.exit(1)

print(f"OK: all {len(flagged)} un-revoked SECURITY DEFINER functions are allowlisted; no new violations.")
PY
